name: Build and Package

on:
  push:
    tags:
      - 'v*'  # Запускать workflow только при push тегов, начинающихся с "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Обязательно для получения тегов

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure

    - name: Create DEB package
      run: |
        cd build
        make package  # Use make package to create the DEB

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-packages
        path: build/*.deb

    - name: Extract tag name
      id: extract_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      env:
        GITHUB_REF: ${{ github.ref }}

    - name: Create Release
      if: github.ref_type == 'tag'  #Подстраховка, чтобы запустить только при теге
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        files: build/*.deb
        body: "Automatically built DEB package"
        name: Release ${{ env.TAG_NAME }}  #Имя релиза
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
