name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERSION: 1.0.0  # Добавлено явное определение версии

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Добавлены права для создания релиза

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev debhelper  # Добавлен debhelper для DEB пакетов

    - name: Create build directory
      run: mkdir -p build  # Добавлен -p для избежания предупреждений

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure

    - name: Create packages
      run: |
        cd build
        cpack -G "DEB;TGZ"  # Явно указываем генерацию DEB и TGZ пакетов

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: |  # Обновлены пути к артефактам
          build/*.deb
          build/*.tar.gz

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}  # Используем определенную версию
        name: Release v${{ env.VERSION }}
        body: "Automated release with built packages"
        files: |  # Обновлены пути к файлам
          build/*.deb
          build/*.tar.gz
        draft: false
        prerelease: false
